[project]
name = "oracle-db-doc-mcp-server"
version = "1.0.2"
description = "The Oracle Database Documentation MCP Server"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.9.0",
    "fastmcp==3.2.4",
    "markdownify>=1.2.0",
    "pocketsearch>=0.40.0",
    "pydantic>=2.12.3"
]

[dependency-groups]
dev = [
    "pytest>=9.0.3",
    "pytest-cov>=7.0.0",
]

[tool.coverage.run]
omit = [
    "test_*.py",
    "dist/*",
    ".venv/*",
]

[tool.coverage.report]
precision = 2
fail_under = 90
